# Generated by Django 2.1.7 on 2019-05-25 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('surveyhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter the Survey question', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(help_text='Enter the type of question', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseCollector',
            fields=[
                ('responseid', models.UUIDField(default=uuid.uuid4, help_text='Response ID', primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=500)),
                ('questionarieid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveyhome.Questionarie')),
            ],
            options={
                'ordering': ['surveyid'],
            },
        ),
        migrations.CreateModel(
            name='SurveyTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the survey', max_length=200)),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveyhome.Logo')),
                ('surveytype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveyhome.SurveyType')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profilepic', models.ImageField(blank=True, upload_to='userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='responsecollector',
            name='surveyid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveyhome.SurveyTitle'),
        ),
        migrations.AddField(
            model_name='questionarie',
            name='questiontype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveyhome.QuestionType'),
        ),
        migrations.AddField(
            model_name='questionarie',
            name='surveyid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveyhome.SurveyTitle'),
        ),
    ]
